from __future__ import annotations

from typing import TYPE_CHECKING
from typing import Any
from typing import Protocol

if TYPE_CHECKING:
    from datetime import datetime
    from pathlib import Path


class ProcessRuntimePort(Protocol):
    def find_process(self, app_path: Path) -> Any | None: ...

    def load_process(self, pid: int) -> Any: ...

    def is_process_running(self, process: Any) -> bool: ...

    def process_status(self, process: Any) -> str: ...

    def process_create_time(self, process: Any) -> float: ...

    def terminate_process(self, process: Any) -> None: ...

    def kill_process(self, process: Any) -> None: ...

    def wait_process(self, process: Any, timeout: float) -> None: ...

    def get_process_info(self, process: Any) -> dict[str, Any]: ...

    def human_datetime_short(self, value: datetime) -> str: ...

    def now_utc(self) -> datetime: ...
